export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const GET_DESTINATION_BY_ID = "GET_DESTINATION_BY_ID";
export const LIKE_DESTINATION = "LIKE_DESTINATION";
export const ADD_REVIEW = "ADD_REVIEW";
